### ISSUE TITLE
Culture Collection of Autotrophic Organisms

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#2038] opened 2023-10-03 09:59 UTC
## Culture Collection of Autotrophic Organisms
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/960e499d-08d0-44c7-8804-239a04a9069b
**Code**: `CCALA`
**Homepage**: http://www.butbn.cas.cz/ccala/ccala.htm
**Fuzzy name search in GBIF publisher**:
`None`

**Number of linked occurrences**: `0` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=960e499d-08d0-44c7-8804-239a04a9069b)

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [x]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by spalp** [comment] 2024-02-08 21:09
It is a collection. Duplicate of [Culture Collection of Autotrophic Organisms](https://registry.gbif.org/collection/1232c786-1ace-4b47-a115-9917f6fd05a6)

**Closed** 2024-02-08 21:10 UTC
Labels: CZ, duplicate
