### ISSUE TITLE
National University of Singapore

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#1370] opened 2022-03-24 13:26 UTC
##National University of Singapore
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/35110a2f-51fc-49ad-b7d5-509187308107
**Code**: `SINU`
**Fuzzy name search in GBIF publisher**:
* [Lee Kong Chian Natural History Museum, National University of Singapore](https://www.gbif.org/publisher/14c4c7da-fb56-44f7-9589-76bd670bf8a7)

**Number of linked occurrences**: `0` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=35110a2f-51fc-49ad-b7d5-509187308107)

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [x]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by lilee-sh** [comment] 2023-01-04 09:45
- The collection of this institution is currently under the Lee Kong Chain Natural History Museum . Hence is a duplicate of the issue https://github.com/gbif/collection-mobilization/issues/1367
- The institution is merged with LKCNHM in GRSciColl and the issue here is closed.

**Closed** 2023-01-04 09:46 UTC
Labels: SG
